export const EMPTY_ARRAY = [];
export const EMAIL = 'Email';
export const COUNTRY = 'Country';
export const DATE_JOINED = 'Date Joined';
export const DOB = 'DOB';
export const LOCATION = 'Location';
export const CITY = 'city';
export const STATE = 'state';
export const POSTCODE = 'postcode';
export const NONE = "none";
export const LARGE = "large";
export const ERROR = 'Error';
export const SOMETHING_WRONG = 'Something wrong'